export const history = [
  {
    id: "1",
    res: "win",
    mode: "blind",
    name: "국이",
    prevRating: "1248",
    rating: "1366",
  },
  {
    id: "2",
    res: "lose",
    mode: "normal",
    name: "시니",
    prevRating: "1366",
    rating: "1277",
  },
  {
    id: "3",
    res: "win",
    mode: "emotion",
    name: "무력의 보안관 정준",
    prevRating: "1277",
    rating: "1499",
  },
  {
    id: "4",
    res: "lose",
    mode: "emotion",
    name: "말 잘타는 현구",
    prevRating: "1499",
    rating: "1435",
  },
  {
    id: "5",
    res: "win",
    mode: "normal",
    name: "MZ 한나",
    prevRating: "1435",
    rating: "1611",
  },
  {
    id: "6",
    res: "win",
    mode: "blind",
    name: "황야의 무법자",
    prevRating: "1611",
    rating: "1800",
  },
  {
    id: "6",
    res: "win",
    mode: "blind",
    name: "황야의 무법자",
    prevRating: "1800",
    rating: "2023",
  },
];

export const myInfoTest = {
  tier: "J",
  nickname: "현쿠",
  reward: "10",
  totalMatches: "11",
  wins: "7",
};
